name: build and test pipeline
on:
  push:
    branches:
      - feature/*

jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Checkout from git repository
        run: git checkout ${{ github.ref }}
  
  
      - name: Setup java 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
  
      - name: Build with Maven
        run: |
          mvnw clean package
          echo 'Build completed'
